title: Jorge Vargas Silva
author: Jorge Vargas Silva
description: Notes from a software developer in Santiago, Chile.
url: "https://jorgevargas.io"
timezone: "America/Santiago"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-turbo

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - tags
